"""picture column added to Workshop table

Revision ID: 07c08ac76908
Revises: 80b628c994fc
Create Date: 2022-04-24 11:56:59.181421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07c08ac76908'
down_revision = '80b628c994fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workshop', sa.Column('picture_url', sa.String(length=260), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workshop', 'picture_url')
    # ### end Alembic commands ###
