"""fourth

Revision ID: 333f4a957857
Revises: e5206268eee4
Create Date: 2022-04-27 18:17:21.668001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '333f4a957857'
down_revision = 'e5206268eee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=40), nullable=True))
    # ### end Alembic commands ###
