"""name column added

Revision ID: 40464014f602
Revises: 9d976217d55e
Create Date: 2022-04-20 14:47:48.948890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40464014f602'
down_revision = '9d976217d55e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
