"""second

Revision ID: 4921fa3ff331
Revises: e9650ab25e96
Create Date: 2022-04-27 18:16:21.873745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4921fa3ff331'
down_revision = 'e9650ab25e96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###
