"""my third migration

Revision ID: 80b628c994fc
Revises: 939d39e24e33
Create Date: 2022-04-22 17:14:28.269606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80b628c994fc'
down_revision = '939d39e24e33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workshop', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workshop', 'date')
    # ### end Alembic commands ###
