"""my second migration

Revision ID: 939d39e24e33
Revises: f33c94ea7e8c
Create Date: 2022-04-22 17:09:13.911115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '939d39e24e33'
down_revision = 'f33c94ea7e8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workshop', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workshop', sa.Column('date', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
