"""my first migration

Revision ID: 9935806dd440
Revises: 
Create Date: 2022-04-22 11:18:40.372773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9935806dd440'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first', sa.String(length=10), nullable=True),
    sa.Column('second', sa.String(length=10), nullable=True),
    sa.Column('third', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=40), nullable=True),
    sa.Column('password', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('password')
    )
    op.create_table('dance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first', sa.String(length=20), nullable=True),
    sa.Column('second', sa.String(length=20), nullable=True),
    sa.Column('third', sa.String(length=20), nullable=True),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['level_id'], ['level.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dance')
    op.drop_table('user')
    op.drop_table('level')
    # ### end Alembic commands ###
