"""email column deleted

Revision ID: d88fd71aba98
Revises: a0ca6b54cd01
Create Date: 2022-04-27 19:50:39.471789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd88fd71aba98'
down_revision = 'a0ca6b54cd01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=120), nullable=True))
    # ### end Alembic commands ###
